#!/bin/bash
# See https://github.com/adriancooney/Taskfile for examples

# Sane error handling 
set -o errexit -o pipefail

### FUNCTIONS GO HERE
function default {
	: "Runs a default task"
	launch "$@"
}

function launch {
	: "Run the launcher"
	poetry run starlaunch "$@"
}

function build {
	: "Build a distributable executable from the program"
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    make dist/StarLaunch
  elif [[ "$OSTYPE" == "msys" ]]; then
    make dist/StarLaunch.exe
  fi
}

function clean {
	: "Removes ignored files to clean the working tree"
	git clean -xfd .
}

function wheel {
	: "Build a wheel (and other formats) to distribute my python package"
	make "dist/starlaunch-$(poetry version -s)-py3-none-any.whl"
}

function publish {
	: "Publish this package to PyPi"
	wheel
	poetry publish --username the-nick-of-time
}

### /FUNCTIONS GO HERE

function help {
	: "Auto-generate list of tasks, including documentation in the form of these noop statements"
	compgen -A function | while read -r name ; do
		paste <(printf '%s' "${name}") <(type "$name" | sed -rn 's/^[[:space:]]*: "(.*)";?/\1/p')
	done
}
if [[ $# -eq 0 ]] ; then
	default
else
	"$@"
fi
